[project]
name = "retrosynformer"
version = "0.1.1"
description = "RetroSynFormer"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "alembic",
    "annotated-types",
    "apted",
    "black",
    "boto3",
    "botocore",
    "bottle",
    "brotli",
    "cachedmethods",
    "certifi",
    "cython",
    "cycler",
    "contourpy",
    "pydantic",
    "dask",
    "dill",
    "pandas",
    "sympy==1.13.1",
# uv pip install torch --index-url https://download.pytorch.org/whl/rocm6.2
#    "-e ../rdchiral/",
    "numpy",
    "pandas",
    "partd",
    "rdkit",
    "reaction-utils==1.9.3",    # "reaction-utils",
    "scipy",
    "scikit-learn",
    "matplotlib",
    "seaborn",
    "markupsafe",
    "huggingface-hub",
    "filelock",
    "markupsafe",
    "transformers",
]
# packages = [
#      "retrosynformer",
# ]

# [tool.uv]
# exclude-newer="3 weeks"

